// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A closed classification of the error variant, never derived from error text.
 */
export type ExecutionErrorCategory = "invalidRequest" | "encoding" | "connection" | "timeout" | "stream" | "fatal" | "io" | "other";
