// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The boundary at which an otherwise unclassified execution error was observed.
 */
export type ExecutionErrorStage = "requestPreparation" | "transport" | "providerResponse" | "streamProcessing";
