// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structural tool fields only; JSON Schema property names are never retained.
 */
export type ProviderToolField = "type" | "name" | "description" | "parameters" | "strict" | "format";
