// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderToolLocation } from "./ProviderToolLocation";
import type { ProviderValidationCode } from "./ProviderValidationCode";
import type { ProviderValidationParameter } from "./ProviderValidationParameter";

/**
 * Null fields explicitly represent unavailable or unrecognized validation detail.
 */
export type ProviderValidation = { code: ProviderValidationCode | null, parameter: ProviderValidationParameter | null,
/**
 * Available only for recognized, bounded `tools` locations.
 */
toolLocation: ProviderToolLocation | null, };
