// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Root request parameter categories, never provider-supplied field names.
 */
export type ProviderValidationParameter = "model" | "serviceTier" | "reasoning" | "tools" | "input" | "text" | "toolChoice" | "parallelToolCalls" | "instructions" | "include" | "store" | "stream" | "previousResponseId" | "clientMetadata" | "promptCacheKey";
