// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderToolField } from "./ProviderToolField";

/**
 * A tool slot, optionally inside one namespace, with an optional structural field.
 * Indices are limited to 0..=65535; null `field` identifies the tool object itself.
 */
export type ProviderToolLocation = { toolIndex: number, nestedToolIndex: number | null, field: ProviderToolField | null, };
